[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/sitemap.xml"
to = "https://gossipphub-backend.onrender.com/sitemap.xml"
status = 200
force = true

[[redirects]]
from = "/api/*"
to = "https://gossipphub-backend.onrender.com/api/:splat"
status = 200
force = true